### ISSUE TITLE
link to /lib/init/upstart-job needed?

### ISSUE THREAD

**Issue by schrepfler** [Spantree/puppet-upstart#1]
When trying to make a simple job as in the example, on RHEL6 the service links to /lib/init/upstart-job (which is not there).
Is this needed as the links is broken?

**Comment by feniix** [comment]
@schrepfler sorry for the delay in answering, the module was not tested with centos/rhel 6

If you feel like adding the support I am open to receiving PRs

**Comment by schrepfler** [comment]
Hi Feliix, I haven't really worked on this that much since then. As distros have moved on to systemd I'm not sure how important it is anymore.
